[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[phases.install]
cmds = [
  "npm ci --no-audit --no-fund"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "node start.js"