name: Deploy to Spaceship Hosting

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build application
        run: npm run build
        
      - name: Deploy to Spaceship via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SPACESHIP_HOST }}
          username: ${{ secrets.SPACESHIP_USERNAME }}
          password: ${{ secrets.SPACESHIP_PASSWORD }}
          protocol: ftps
          port: 21
          security: loose
          timeout: 300000
          retry: 3
          log-level: verbose
          local-dir: ./dist/
          server-dir: /
          exclude: |
            .git*
            .github*
            node_modules*
            **/*.md
            **/*.log
            .env*
            src/
            client/src/
            
      - name: Notify deployment success
        run: |
          echo "✅ Deployment completed successfully"
          echo "🌐 Website: https://your-domain.com"
          echo "⏰ Deployed at: $(date)"